SleepMakeSense/Models/DiaryData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

// 20171023 Pandita: reimplement using EF
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;

namespace SleepMakeSense.Models
{
    public class DiaryData
    {
        [Key]
        public int Id { get; set; }
        //public Guid Id { get; set; }

        // Foreign key to AspNetUser
        [ForeignKey("AspNetUser")]
        public string AspNetUserId { get; set; }
        public AspNetUser AspNetUser { get; set; }

        public DateTime DateStamp { get; set; }
        public string WakeUpFreshness { get; set; }
        public string Mood { get; set; }
        public string Stress { get; set; }
        public string Tiredness { get; set; }
        public string Dream { get; set; }
        public string BodyTemp { get; set; }
        public string Hormone { get; set; }
        public string SchoolStress { get; set; }
        public string CoffeeAmt { get; set; }
        public string CoffeeTime { get; set; }
        public string AlcoholAmt { get; set; }
        public string AlcoholTime { get; set; }
        public string NapTime { get; set; }
        public string NapDuration { get; set; }
        public string DigDeviceDuration { get; set; }
        public string GamesDuration { get; set; }
        public string SocialFamily { get; set; }
        public string SocialFriend { get; set; }
        public string MusicDuration { get; set; }
        public string TVDuration { get; set; }
        public string WorkTime { get; set; }
        public string WorkDuration { get; set; }
        public string ExerciseDuration { get; set; }
        public string ExerciseIntensity { get; set; }
        public string DinnerTime { get; set; }
        public string SnackTime { get; set; }
        public string AmbientHumd { get; set; }
        public string SunRiseTime { get; set; }
        public string SunSetTime { get; set; }
        public string SocialMedia { get; set; }

        public string AmbientTemp { get; set; }
        public string Light { get; set; }
        public string Noise { get; set; }
        public string Cleanliness { get; set; }
        public string Medication { get; set; }

        // customizable factors
        public string PerFactor1 { get; set; }
        public string PerFactor2 { get; set; }
        public string PerFactor3 { get; set; }
        public string PerFactor4 { get; set; }
        public string PerFactor5 { get; set; }
        public string PerFactor6 { get; set; }

        /*public void Add(Models.DiaryData diaryData)
        {
            throw new NotImplementedException();
        }*/

    }
}

SleepMakeSense/Controllers/DiaryDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Net;

using SleepMakeSense.Models;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using SleepMakeSense.DataAccessLayer;
using System.Data.Entity.Core.Objects;

namespace SleepMakeSense.Controllers
{
    public class DiaryDataController : Controller
    {
        private SleepbetaDataContext Db = new SleepbetaDataContext();

        [HttpGet]
        public ActionResult DiaryDataSetup()
        {
            DiaryDataSetupModel diaryDataSetupData = new DiaryDataSetupModel();
            // Might want to load the data and assign it to the model.

            // 20171023 Pandita: LINQ-to-SQL replaced by EF
            //IEnumerable<UserQuestions> dataQuery = from table in Db.UserQuestions
            //                where table.AspNetUserId.Equals(System.Web.HttpContext.Current.User.Identity.GetUserId())
            //                select table;

            var CurrentUserId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            IEnumerable<UserQuestions> dataQuery = from table in Db.UserQuestions
                                                   where table.AspNetUserId.Equals(CurrentUserId)
                                                   select table;

            bool previousEntry = false;

            foreach (UserQuestions entry in dataQuery)
            {
                if (entry.AspNetUserId == CurrentUserId)
                {
                    diaryDataSetupData.userQuestions = entry;
                    previousEntry = true;
                }
            }
            if(!previousEntry)
            {
                diaryDataSetupData.userQuestions = new UserQuestions() { AspNetUserId = CurrentUserId };
            }

            return View(diaryDataSetupData);//);
        }

        // Retrieve action from browser and stored in db
        /// <summary>
        /// This Method submits the questions to ask the user.
        /// this is done by looking for any previous entry and updating it.
        /// If it is unable to do so, it will submit a new entry
        /// </summary>
        /// <param name="diaryDataSetupData"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DiaryDataSetup(DiaryDataSetupModel diaryDataSetupData)
        {
            // 20171023 Pandita: refactoring from LINQ-to-SQL to EF
            //IEnumerable<UserQuestions> dataQuery = from table in Db.UserQuestions
            //                                      where table.AspNetUserId.Equals(System.Web.HttpContext.Current.User.Identity.GetUserId())
            //                                     select table;

            var CurrentUserId = System.Web.HttpContext.Current.User.Identity.GetUserId();
            IEnumerable<UserQuestions> dataQuery = from table in Db.UserQuestions
                                                   where table.AspNetUserId.Equals(CurrentUserId)
                                                   select table;
            bool recordPresent = false;

            foreach (UserQuestions entry in dataQuery)
            {
            if (entry.AspNetUserId == CurrentUserId)
                {
                    // 19 categories, hormone not appear on UI for the time being, need to implement a drop-down list for it with date. So in total, 18 categories to choose from.
                    // careful!! some are "question" and others are "questions"
                    recordPresent = true;
                entry.WakeUpFreshness = diaryDataSetupData.userQuestions.WakeUpFreshness;
                entry.Mood = diaryDataSetupData.userQuestions.Mood; // 20170214 Pandita: this one not appear on UI
                entry.Stress = diaryDataSetupData.userQuestions.Stress;
                entry.Tiredness = diaryDataSetupData.userQuestions.Tiredness;
                entry.Dream = diaryDataSetupData.userQuestions.Dream;
                entry.SchoolQuestions = diaryDataSetupData.userQuestions.SchoolQuestions;
                entry.CoffeeQuestions = diaryDataSetupData.userQuestions.CoffeeQuestions;
                entry.AlcoholQuestions = diaryDataSetupData.userQuestions.AlcoholQuestions;
                entry.NapQuestions = diaryDataSetupData.userQuestions.NapQuestions;
                entry.DigDeviceDurationQuestion = diaryDataSetupData.userQuestions.DigDeviceDurationQuestion;
                entry.GameDurationQuestion = diaryDataSetupData.userQuestions.GameDurationQuestion;
                entry.SocialMediaDurationQuestion = diaryDataSetupData.userQuestions.SocialMediaDurationQuestion;
                entry.SocialActivityDurationQuestion = diaryDataSetupData.userQuestions.SocialActivityDurationQuestion;
                entry.MusicDurationQuestion = diaryDataSetupData.userQuestions.MusicDurationQuestion;
                entry.TVDurationQuestion = diaryDataSetupData.userQuestions.TVDurationQuestion;
                entry.WorkQuestions = diaryDataSetupData.userQuestions.WorkQuestions;
                entry.ExersiseQuestions = diaryDataSetupData.userQuestions.ExersiseQuestions;
                entry.FoodQuestions = diaryDataSetupData.userQuestions.FoodQuestions;
                entry.GenderHormoneQuestion = diaryDataSetupData.userQuestions.GenderHormoneQuestion;

                //Pandita: added new factors on 2018/3/30
                entry.TempQuestion = diaryDataSetupData.userQuestions.TempQuestion;
                entry.LightQuestion = diaryDataSetupData.userQuestions.LightQuestion;
                entry.NoiseQuestion = diaryDataSetupData.userQuestions.NoiseQuestion;
                entry.CleanlinessQuestion = diaryDataSetupData.userQuestions.CleanlinessQuestion;
                entry.MedicationQuestion = diaryDataSetupData.userQuestions.MedicationQuestion;
                entry.PerFactor1Question = diaryDataSetupData.userQuestions.PerFactor1Question;
                entry.PerFactor1Name = diaryDataSetupData.userQuestions.PerFactor1Name;
                    /*
                entry.PerFactor2Question = diaryDataSetupData.userQuestions.GenderHormoneQuestion;
                entry.PerFactor3Question = diaryDataSetupData.userQuestions.GenderHormoneQuestion;
                entry.PerFactor4Question = diaryDataSetupData.userQuestions.GenderHormoneQuestion;
                entry.PerFactor5Question = diaryDataSetupData.userQuestions.GenderHormoneQuestion;
                entry.PerFactor6Question = diaryDataSetupData.userQuestions.GenderHormoneQuestion;
                */

                }
            }

            if (recordPresent == false)
            {
                diaryDataSetupData.userQuestions.AspNetUserId = CurrentUserId;
                //Db.UserQuestions.InsertOnSubmit(diaryDataSetupData.userQuestions);
                Db.UserQuestions.Add(diaryDataSetupData.userQuestions);
            }

            // 20171022 Pandita: unified with EF
            //Db.SubmitChanges();
            Db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public ActionResult EnterDiaryData()
        {
            if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
            {
                //Setting up the Selection for the questions
                DiaryDataViewClass viewModel = new DiaryDataViewClass();
                viewModel.QUESTIONSELECTION = new QuestionsSelections();

                //Getting the current User for DB lookup
                string userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
                // 20170213 Pandita: why is this maginc number 5 ???
                DateTime dateStop = DateTime.UtcNow.Date.AddDays(-5);

                //Looking up the questions for the user
                UserQuestions userQuestion = (from table in Db.UserQuestions
                                where table.AspNetUserId.Equals(userId)
                                select table).First();
                viewModel.UserQuestion = userQuestion;

                //Looking up for previously saved data
                // 20171023 Pandita: refactoring from LINQ-to-SQL to EF
                // IEnumerable<DiaryData> dataQuery = from table in Db.DiaryData
                //                                     where table.AspNetUserId.Equals(userId) && table.DateStamp.Date == DateTime.UtcNow.Date
                //                                   select table;

                var currentTime = DateTime.UtcNow.Date;
                IEnumerable<DiaryData> dataQuery = from table in Db.DiaryData
                                                   where table.AspNetUserId.Equals(userId) && System.Data.Entity.DbFunctions.TruncateTime(table.DateStamp) == currentTime
                                                   select table;

                bool todaysData = false;
                
                foreach (DiaryData diaryData in dataQuery)
                { 
                        viewModel.DiaryData = diaryData;
                        todaysData = true;
                }

                if (!todaysData)
                {
                    viewModel.DiaryData = new DiaryData() { AspNetUserId = userId };
                }

                //Checking if the data is valid and directing to the page
                if (userQuestion.AspNetUserId == userId)
                    {
                        //For AM/PM based questions - not yet fully implemented
                      //  if (DateTime.UtcNow.AddHours(10).ToString("tt") == "AM") viewModel.Morning = true;
                        return View(viewModel);
                    }

SleepMakeSense/Views/DiaryData/DiaryDataSetup.cshtml
@using SleepMakeSense.Models

@model DiaryDataSetupModel



<!DOCTYPE html>
@using (Html.BeginForm("DiaryDataSetup", "DiaryData", FormMethod.Post))
{
    <html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Factor List</title>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" charset="utf-8"></script>
    </head>


    <body onload="DiaryDataController.html()">
        <div id="DataProcessing">
            <script type="text/javascript">
            </script>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>Sleep Diary</h2>
                    <p>Setting Up Diary Questions.</p>
                    <hr />
                </div>
            </div>

            <table class="table">
                <tr class="tr-noborder">
                    <td class="diaryfactor"><i class="fa fa-child fa-2x"></i><span>Wake Up Freshness</span></td>
                    <td class="diaryquestion">Asked Question - How fresh did you feel from last nights sleep? (1 not at all - 5 very)</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.WakeUpFreshness)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-cloud fa-2x"></i><span>Dream</span></td>
                    <td class="diaryquestion">Asked Question - How well did you remember your dream? (1 not at all - 5 very)</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.Dream)
                    </td>
                </tr>

                <tr class="tr-noborder">
                    <td class="diaryfactor"><i class="fa fa-frown-o fa-2x"></i><span>Stress</span></td>
                    <td class="diaryquestion">Asked Question - How anxious/stressed were you yesterday? (1 not at all - 5 very)</td>
                    <td>
                      @Html.CheckBoxFor(Model => Model.userQuestions.Stress)
                    </td>
                </tr>
                <tr class="tr-noborder">
                    <td class="diaryfactor"><i class="fa fa-child fa-2x"></i><span>Tiredness</span></td>
                    <td class="diaryquestion">Asked Question - How tired/sleepy were you yesterday? (1 not at all - 5 very)</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.Tiredness)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-child fa-2x"></i><span>Mood</span></td>
                    <td class="diaryquestion">Asked Question - How was your mood before bed? (1 very bad - 5 very good)</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.Mood)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-graduation-cap fa-2x"></i><span>School Questions</span></td>
                    <td class="diaryquestion">Asked Question - How anxious/stressed were you in regards to school exams and assignments yesterday?  (1 not at all - 5 very)</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.SchoolQuestions)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-coffee fa-2x"></i><span>Coffees Questions</span></td>
                    <td class="diaryquestion">Asked Question - How many caffeinated beverages & Time of the last caffeinated beverage </td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.CoffeeQuestions)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-glass fa-2x"></i><span>Alcohol Questions</span></td>
                    <td class="diaryquestion">Asked Question - How many alcoholic beverages & Time of the last alcoholic beverage</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.AlcoholQuestions)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-bed fa-2x"></i><span>Nap Questions</span></td>
                    <td class="diaryquestion">Asked Question - What Time was your nap & How long did you nap yesterday</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.NapQuestions)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-users fa-2x"></i><span>Social Activities Question</span></td>
                    <td class="diaryquestion">Asked Question - How long did you spend with your family or friends after 6pm last night?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.SocialActivityDurationQuestion)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-mobile fa-2x"></i><span>Digital Device Question</span></td>
                    <td class="diaryquestion">Asked Question - How long did you spend on your phone/tablet for after 6pm last night?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.DigDeviceDurationQuestion)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-gamepad fa-2x"></i><span>Games Question</span></td>
                    <td class="diaryquestion">Asked Question - How long did you spend on video games for after 6pm last night?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.GameDurationQuestion)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-facebook fa-2x"></i><span>Social Media Question</span></td>
                    <td class="diaryquestion">Asked Question - How long did you spend on social media for after 6pm last night?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.SocialMediaDurationQuestion)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-headphones fa-2x"></i><span>Music Question</span></td>
                    <td class="diaryquestion">Asked Question - How long did spend listerning to music after 6pm last night?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.MusicDurationQuestion)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-bed fa-2x"></i><span>TV Question</span></td>
                    <td class="diaryquestion">Asked Question - How long did spend watching TV after 6pm last night?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.TVDurationQuestion)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-briefcase fa-2x"></i><span>Work Questions</span></td>
                    <td class="diaryquestion">Asked Question - When did you start work yesterday? & How long were you at work?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.WorkQuestions)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-futbol-o fa-2x"></i><span>Excersise Questions</span></td>
                    <td class="diaryquestion">Asked Question - How long & how intense & How instense was your workout?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.ExersiseQuestions)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-cutlery fa-2x"></i><span>Food Questions</span></td>
                    <td class="diaryquestion">Asked Question - When was your dinner last night? & What time did you snack last night?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.FoodQuestions)
                    </td>
                </tr>

                @*Pandita: added on 2018/3/30*@
                <tr>
                    <td class="diaryfactor"><i class="fa fa-fire fa-2x"></i><span>Temperature Questions</span></td>
                    <td class="diaryquestion">Asked Question - How warm or cold was your room when you fell asleep?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.TempQuestion)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-lightbulb-o fa-2x"></i><span>Light Questions</span></td>
                    <td class="diaryquestion">Asked Question - How much light was visible in your room before falling asleep? </td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.LightQuestion)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-volume-up fa-2x"></i><span>Noise Questions</span></td>
                    <td class="diaryquestion">Asked Question - How much noise was present before falling asleep?</td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.NoiseQuestion)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-magic fa-2x"></i><span>Cleanliness Questions</span></td>
                    <td class="diaryquestion">Asked Question - Last night, how clean was your room? </td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.CleanlinessQuestion)
                    </td>
                </tr>
                <tr>
                    <td class="diaryfactor"><i class="fa fa-user-md fa-2x"></i><span>Medication Questions</span></td>
                    <td class="diaryquestion">Asked Question - Did you take your medication today? </td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.MedicationQuestion)
                    </td>
                </tr>

                <tr class="tr-noborder">
                    <td class="diaryfactor"><i class="fa fa-user-plus fa-2x"></i><span>Personal Factor</span></td>
                    <td class="diaryquestion">Asked Question - How would you rate your personal factor? </td>
                    <td>
                        @Html.CheckBoxFor(Model => Model.userQuestions.PerFactor1Question)
                    </td>
                </tr>
                <tr >
                    <td></td>
                    <td> Please enter the name for the personal factor @Html.TextBoxFor(Model => Model.userQuestions.PerFactor1Name)</td>
                    <td></td>
                </tr>


                <tr class="tr-nobg">
                    <td></td>
                    <td></td>
                    <td><input type="submit" value="Save" class="btn btn-primary btn-lg btn-block" /></td>
                </tr>
            </table>
        </div>
    </body>
</html>
}