SleepMakeSense/Controllers/FitbitController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Configuration;
using System.Threading.Tasks;
using SleepMakeSense.Models;
using System.Data.SqlClient;
//Fitbit Portable
using Fitbit.Models;
//UserControll Intergration
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using MathNet.Numerics.Statistics;
using Microsoft.AspNet.Identity;
using SleepMakeSense.DataAccessLayer;
using System.Data.Sql;

namespace SleepMakeSense.Controllers
{
    public class FitbitController : Controller
    {
        //
        // GET: /Fitbit/

        private SleepbetaDataContext Db = new SleepbetaDataContext();

        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        //
        // GET: /FitbitAuth/
        // Setup - prepare the user redirect to Fitbit.com to prompt them to authorize this app.
        public ActionResult Authorize()
        {
            var appCredentials = new FitbitAppCredentials()
            {
                ClientId = ConfigurationManager.AppSettings["FitbitClientId"],
                ClientSecret = ConfigurationManager.AppSettings["FitbitClientSecret"]
            };
            //make sure you've set these up in Web.Config under <appSettings>:

            Session["AppCredentials"] = appCredentials;

            //Provide the App Credentials. You get those by registering your app at dev.fitbit.com
            //Configure Fitbit authenticaiton request to perform a callback to this constructor's Callback method
            var authenticator = new OAuth2Helper(appCredentials, Request.Url.GetLeftPart(UriPartial.Authority) + "/Fitbit/Callback");
            string[] scopes = new string[] { "profile", "activity", "sleep", "weight", "nutrition" };

            string authUrl = authenticator.GenerateAuthUrl(scopes, null);

            return Redirect(authUrl);
        }

        //Final step. Take this authorization information and use it in the app
        public async Task<ActionResult> Callback()
        {
            
            FitbitAppCredentials appCredentials = (FitbitAppCredentials)Session["AppCredentials"];

            var authenticator = new OAuth2Helper(appCredentials, Request.Url.GetLeftPart(UriPartial.Authority) + "/Fitbit/Callback");

            string code = Request.Params["code"];

            OAuth2AccessToken accessToken = await authenticator.ExchangeAuthCodeForAccessTokenAsync(code);

            /*Console.WriteLine("Zilu-debug");
            Console.Write(accessToken);
            Console.WriteLine(accessToken);*/

            //Store credentials in FitbitClient. The client in its default implementation manages the Refresh process
            FitbitClient fitbitClient = GetFitbitClient(accessToken);

            //20171025 Pandita: removed saving tokens
            //SyncFitbitCred(accessToken);

            //return RedirectToAction("Index", "Home");
            return RedirectToAction("Sync", "UserDatas"); // redirect to UserdatasController.cs/Sync().


        }

        // 20171026 Pandita: Mejor no poner token en DB
        /*
        // Add user token to the the TokenManagement Table in DB
        private void SyncFitbitCred(OAuth2AccessToken accessToken)
        {
            if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
            {

                string userId = System.Web.HttpContext.Current.User.Identity.GetUserId();
                var userToken = from table in Db.TokenManagement
                                where table.AspNetUserId.Equals(userId)
                                select table;
                bool tokenAvailable = false;

                foreach (TokenManagement token in userToken)
                {
                    if (token.AspNetUserId == System.Web.HttpContext.Current.User.Identity.GetUserId())
                    {
                        tokenAvailable = true;
                        token.DateChanged = DateTime.UtcNow;
                        token.Token = accessToken.Token;
                        token.TokenType = accessToken.TokenType;
                        token.ExpiresIn = accessToken.ExpiresIn;
                        token.RefreshToken = accessToken.RefreshToken;
                    }
                }

                if (tokenAvailable == false)
                {
                    TokenManagement token = new TokenManagement()
                    {
                    AspNetUserId = System.Web.HttpContext.Current.User.Identity.GetUserId(),
                    DateChanged = DateTime.UtcNow,
                    Token = accessToken.Token,
                    TokenType = accessToken.TokenType,
                    ExpiresIn = accessToken.ExpiresIn,
                    RefreshToken = accessToken.RefreshToken
                };
                    
                    //Db.TokenManagement.InsertOnSubmit(token);
                    Db.TokenManagement.Add(token);
                }


                // 20171022 Pandita: unify with EF
                // Db.SubmitChanges();
                Db.SaveChanges();
            }
        }
        */
        public ActionResult DirectToSync()
        {
            if (!System.Web.HttpContext.Current.User.Identity.IsAuthenticated)
            {
                throw new Exception("You Must be Loged in to sync Fitbit Data");
            }
            //Loading Session data when the user has does not have Key creds in their session
            FitbitAppCredentials appCredentials = new FitbitAppCredentials()
            {
                ClientId = ConfigurationManager.AppSettings["FitbitClientId"],
                ClientSecret = ConfigurationManager.AppSettings["FitbitClientSecret"]
            };
            Session["AppCredentials"] = appCredentials;

            OAuth2AccessToken accessToken = new OAuth2AccessToken();
            /*
            // 20161108 Pandita
            bool fitbitConnected = false;

            string userId = System.Web.HttpContext.Current.User.Identity.GetUserId(); // Get user ID
            IEnumerable <TokenManagement> userToken = from a in Db.TokenManagement // Get user token
                            where a.AspNetUserId.Equals(userId)
                            select a;

            // 20170828 Pandita: BUG!! should not retrieve token from DB, instead, should replace the token in DB by the new token
            // ************************** TO BE REVISED ********************************************************
            foreach (TokenManagement data in userToken)
            {
                if (data.AspNetUserId == userId && data.ExpiresIn == 28800)
                {
                    fitbitConnected = true;
                    accessToken.Token = data.Token;
                    accessToken.TokenType = data.TokenType;
                    accessToken.ExpiresIn = data.ExpiresIn;
                    accessToken.RefreshToken = data.RefreshToken;
                    accessToken.UserId = data.UserId;
                    accessToken.UtcExpirationDate = data.DateChanged.AddSeconds(data.ExpiresIn);
                }
            } 
            
            // 20170213 Pandita: Possibly more than one Token stored for a user? 
            // 20170828 Pandita: should renew the token in DB?
            if (fitbitConnected == true)
            {
                FitbitClient tempSyncClient = GetFitbitClient(accessToken);
                accessToken = tempSyncClient.AccessToken;
                // 20171026 Pandita: removed
                // SyncFitbitCred(accessToken); // 20170213 Pandita: Add token again to DB.TokenManagements?????
                //     return View("Callback");
                return RedirectToAction("Sync", "UserDatas"); // 20170213 Pandita: Should redirect to UserDatas/Sync() or UserDatas/FitbitDataSync(string UserID) ?????
            }*/

            return Authorize(); // If no token is found, direct user to Fitbit authorization page. 
        }




        /// <summary>
        /// In this example we show how to explicitly request a token refresh. However, FitbitClient V2 on its default implementation provide an OOB automatic token refresh.
        /// </summary>
        /// <returns>A refreshed token</returns>
        public async Task<ActionResult> RefreshToken()
        {
            var fitbitClient = GetFitbitClient();

            ViewBag.AccessToken = await fitbitClient.RefreshOAuth2TokenAsync();

            return View("Callback");
        }

        public async Task<ActionResult> TestToken()
        {
            var fitbitClient = GetFitbitClient();

            ViewBag.AccessToken = fitbitClient.AccessToken;

            ViewBag.UserProfile = await fitbitClient.GetUserProfileAsync();

            return View("TestToken");
        }

      


        /// <summary>
        /// HttpClient and hence FitbitClient are designed to be long-lived for the duration of the session. This method ensures only one client is created for the duration of the session.
        /// More info at: http://stackoverflow.com/questions/22560971/what-is-the-overhead-of-creating-a-new-httpclient-per-call-in-a-webapi-client
        /// </summary>
        /// <returns></returns>
        public FitbitClient GetFitbitClient(OAuth2AccessToken accessToken = null)
        {
            if (Session["FitbitClient"] == null)
            {
                if (accessToken != null)
                {
                    var appCredentials = (FitbitAppCredentials)Session["AppCredentials"];
                    FitbitClient client = new FitbitClient(appCredentials, accessToken);
                    Session["FitbitClient"] = client;
                    return client;
                }

SleepMakeSense/Views/Fitbit/Callback.cshtml
@{
    ViewBag.Title = "Callback";
}
<div class="container">
    <div class="row">
        @if (ViewBag.AccessToken != null)
        {

            <p>FitBit Connected Successfully</p>

        }
        else
        {
            <p>The current session has not been authenticated with fitbit</p>
        }
        <p>@Html.ActionLink("Upload My Fitbit Data", "Sync", "UserDatas", new { }, new { @class = "btn btn-primary" })</p>

        <p><a href="/Userdatas/FactorQuestions" class="btn btn-primary">Testing Factor Questions &raquo;</a></p>

    </div>
</div>

SleepMakeSense/Views/Fitbit/Devices.cshtml
@model SleepMakeSense.Models.Date
@{
    ViewBag.Title = "Devices";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="jumbotron">
    <h1>Fitbit</h1>
    @*this is an old site - is not working since the Oathenicate upgrade*@
    @if (ViewBag.FitbitConnected == false)
    {
        <p><a href="/Fitbit/Authorize" class="btn btn-primary">Connect My Fitbit &raquo;</a></p>
    }
    else
    {
        <p><a href="/Userdatas/Sync" class="btn btn-primary">Upload My Fitbit Data &raquo;</a></p>
        @*
                <p> Please input the date that you want to retrieve your sleep data on :) </p>
                using (Html.BeginForm("SleepIntraDay", "Fitbit"))
                {
                    @Html.TextBoxFor(m => m.Year)
                    @Html.TextBoxFor(m => m.Month)
                    @Html.TextBoxFor(m => m.Day)

            <input type="submit" value="Get Min-by-Min Sleep Data" &raquo />
            }*@
        @*<p><a href="/Fitbit/SleepIntraDay" class="btn btn-primary">Get Min-by-Min Sleep Data &raquo;</a></p>
            <p><a href="/Fitbit/StepIntraDay" class="btn btn-primary">Get Min-by-Min Step Data &raquo;</a></p>*@
    }
</div>

SleepMakeSense/Views/Fitbit/SleepIntraday.cshtml
@using Fitbit.Models
@model List<SleepLog>


@{
    ViewBag.Title = "SleepIntraday";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StepIntraday</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" charset="utf-8"></script>
    <style type="text/css">
        .axis path, .axis line {
            fill: none;
            stroke: #bdbdbd;
            shape-rendering: crispEdges;
            font-size: x-small;
        }

        [class*="col-"] {
            background-clip: padding-box;
            /*border: 10px solid transparent;*/
            border: 2px solid;
            border-color: #bdbdbd;
        }

        div.tooltip {
            position: absolute;
            text-align: center;
            width: 160px;
            height: 36px;
            padding: 2px;
            font: 12px sans-serif;
            color: white;
            background: black;
            border: 0px;
            border-radius: 8px;
            pointer-events: none;
        }
    </style>
</head>
<body>

    <div id="Chart">
        <script type="text/javascript">

    var data = [];

    @foreach (SleepLog result in Model)
            {
                foreach (MinuteData d in result.MinuteData)
                {
         @:data.push({ Time: "@d.DateTime", Value: "@Convert.ToDouble(d.Value)" });
            }
            }


    console.log(data);


    PlotTimeseries(data, "#Chart", "Sleep?");

    function PlotTimeseries(myData, section, sFeature) {

        var w = 1000;
        var h = 500;
        var margin = { top: 30, right: 20, bottom: 200, left: 40 };
        width = w - margin.left - margin.right,
        height = h - margin.top - margin.bottom;
        //parseDate = d3.time.format("%m/%d/%Y").parse;


        var xRange = d3.scale.ordinal()
        .rangeRoundBands([0, width], 0.2);

        var yRange = d3.scale.linear()
        .range([height, 0]);

        var xAxis = d3.svg.axis()
        .scale(xRange)
        .orient("bottom")
        .ticks(1);
        //.tickFormat(d3.time.format("%b %e"));

        var yAxis = d3.svg.axis()
        .scale(yRange)
        .orient("left")
        .ticks(5);

        var chart = d3.select(section).append("svg")
        .attr("width", w)
        .attr("height", h)
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

        myData.forEach(function (d) {
            //d.Time = parseDate(d.Time);
            d.Time = d.Time;
            d.Value = +d.Value;
        });

        xRange.domain(myData.map(function (d) { return d.Time; }));
        yRange.domain([0, d3.max(myData, function (d) { return d.Value })]);

        chart.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis)
        .selectAll("text")
        .style("text-anchor", "end")
        .style("fill", "white")
        .style("stroke", "white")
        .attr("dx", "-.8em")
        .attr("dy", "-.55em")
        .attr("transform", "rotate(-90)");

        chart.append("g")
        .attr("class", "y axis")
        .call(yAxis)
        .append("text")
        .attr("transform", "rotate(-90)")
        .attr("y", 6)
        .attr("dy", ".71em")
        .style("text-anchor", "end")
        .text(sFeature);

        var div = d3.select(section).append("div")
        .attr("class", "tooltip")
        .style("opacity", 0);
        // var formatTime = d3.time.format("%b %e");

        chart.selectAll("rect")
        .data(myData)
        .enter().append("rect")
        .attr("class", "bar")
        .attr("x", function (d) { return xRange(d.Time); })
        .attr("width", xRange.rangeBand())
        .attr("y", function (d) { return yRange(d.Value); })
        .attr("height", function (d) { return (height - yRange(d.Value)); })
        .attr("fill", "#bdbdbd")
        .on("mouseover", function (d) {
            d3.select(this)
            .attr("fill", "#3376bf");

            div.transition()
            .duration(200)
            .style("opacity", 0.9);

            // div.html(formatTime(d.Time) + "<br />" + d.Value)
            div.html(d.Time + "<br />" + d.Value)
            .style("left", (d3.event.pageX - 64) + "px")
            .style("top", (d3.event.pageY - 12) + "px");

        })
        .on("mouseout", function (d) {
            d3.select(this)
            .attr("fill", "#bdbdbd");
            div.transition()
            .duration(500)
            .style("opacity", 0);
        });
    }

        </script>
    </div>    

    <div>
        <table>

            @foreach (SleepLog result in Model)
            {
                foreach (MinuteData data in result.MinuteData) {
                     <tr>
                          <td>@data.DateTime</td>
                          <td>@Convert.ToDouble(data.Value)</td>
                     </tr>
            }
            }
        </table>

        @{
        string combined = "";

        foreach (SleepLog result in Model)
        {
            foreach (MinuteData data in result.MinuteData)
            {
                combined += Convert.ToDouble(data.Value) + ",";
            }
        }
        }
        <p>@combined</p>
    </div>
</body>
</html>

SleepMakeSense/Views/Fitbit/StepIntraday.cshtml
@using Fitbit.Models
@model IntradayData


@{
    ViewBag.Title = "StepIntraday";
    Layout = "~/Views/Shared/_Layout.cshtml";
    }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StepIntraday</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" charset="utf-8"></script>
    <style type="text/css">
        .axis path, .axis line {
            fill: none;
            stroke: #bdbdbd;
            shape-rendering: crispEdges;
            font-size: x-small;
        }

        [class*="col-"] {
            background-clip: padding-box;
            /*border: 10px solid transparent;*/
            border: 2px solid;
            border-color: #bdbdbd;
        }

        div.tooltip {
            position: absolute;
            text-align: center;
            width: 60px;
            height: 60px;
            padding: 2px;
            font: 12px sans-serif;
            background: lightsteelblue;
            border: 0px;
            border-radius: 8px;
            pointer-events: none;
        }
    </style>
</head>
<body>
    <div id="Chart">
        <script type="text/javascript">

            var data = [];

    @foreach (IntradayDataValues d in Model.DataSet) { 
     @:data.push({Time: "@d.Time",Value: "@d.Value"});
        }

            console.log(data);


    PlotTimeseries(data, "#Chart", "Steps");

    function PlotTimeseries(myData, section, sFeature) {

        var w = 1000;
        var h = 500;
        var margin = { top: 30, right: 20, bottom: 200, left: 40 };
        width = w - margin.left - margin.right,
        height = h - margin.top - margin.bottom;
        //parseDate = d3.time.format("%m/%d/%Y").parse;


        var xRange = d3.scale.ordinal()
        .rangeRoundBands([0, width], 0.2);

        var yRange = d3.scale.linear()
        .range([height, 0]);

        var xAxis = d3.svg.axis()
        .scale(xRange)
        .orient("bottom")
        .ticks(8)
        //.tickFormat(d3.time.format("%b %e"));

        var yAxis = d3.svg.axis()
        .scale(yRange)
        .orient("left")
        .ticks(5);

        var chart = d3.select(section).append("svg")
        .attr("width", w)
        .attr("height", h)
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

        myData.forEach(function (d) {
            //d.Time = parseDate(d.Time);
            d.Time = d.Time;
            d.Value = +d.Value;
        });

        xRange.domain(myData.map(function (d) { return d.Time; }));
        yRange.domain([0, d3.max(myData, function (d) { return d.Value })]);

        chart.append("g")
        .attr("class", "x axis")
        .attr("transform", "translate(0," + height + ")")
        .call(xAxis)
        .selectAll("text")
        .style("text-anchor", "end")
        .attr("dx", "-.8em")
        .attr("dy", "-.55em")
        .attr("transform", "rotate(-90)");

        chart.append("g")
        .attr("class", "y axis")
        .call(yAxis)
        .append("text")
        //.attr("transform", "rotate(-90)")
        //.attr("y", 6)
        //.attr("dy", ".71em")
        //.style("text-anchor", "end")
        .text(sFeature);

        var div = d3.select(section).append("div")
        .attr("class", "tooltip")
        .style("opacity", 0);
       // var formatTime = d3.time.format("%b %e");

        chart.selectAll("rect")
        .data(myData)
        .enter().append("rect")
        .attr("class", "bar")
        .attr("x", function (d) { return xRange(d.Time); })
        .attr("width", xRange.rangeBand())
        .attr("y", function (d) { return yRange(d.Value); })
        .attr("height", function (d) { return (height - yRange(d.Value)); })
        .attr("fill", "#bdbdbd")
        .on("mouseover", function (d) {
            d3.select(this)
            .attr("fill", "#3376bf");

            div.transition()
            .duration(200)
            .style("opacity", 0.9);

           // div.html(formatTime(d.Time) + "<br />" + d.Value)
            div.html(d.Time + "<br />" + d.Value)
            .style("left", (d3.event.pageX - 64) + "px")
            .style("top", (d3.event.pageY - 12) + "px");

        })
        .on("mouseout", function (d) {
            d3.select(this)
            .attr("fill", "#bdbdbd");
            div.transition()
            .duration(500)
            .style("opacity", 0);
        });
    }

        </script></div>

        <div>
            <table>
                @foreach (IntradayDataValues intraData in Model.DataSet)
                {
                    <tr>
                        <td>@intraData.Time.ToShortTimeString()</td>
                        <td>@intraData.Value</td>
                    </tr>
                }
            </table>
        </div>
</body>
</html>

SleepMakeSense/Views/Fitbit/Tablero.cshtml
@{
    ViewBag.Title = "DataAnalysis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="jumbotron">
    <h1>Fitbit</h1>
    <!--p class="lead">SleepMakeSense helps you identify personal sleep affecting factors.</p-->

    <p><a href="/Fitbit/Analysis" class="btn btn-default">Analysis Sleep Affecting Factors&raquo;</a></p>
    <p><a href="/Fitbit/Export" class="btn btn-default">Export Data &raquo;</a></p>
    @Html.ActionLink("ViewData", "Index", "Sleeps")
</div>